language: php
php:
    - '7.0'

install: composer install --no-interaction --prefer-source

addons:
    code_climate:
        repo_token: 56d9ca5cbcc0cb5634003d87

after_script:
  - vendor/bin/test-reporter
