language: php
php:
    - '7.0'

install: composer install --no-interaction --prefer-source

addons:
    code_climate:
        repo_token: 8f1b95eef403d715c37313a6e5903cdd324735acb7a2d221534f8da285ff3dc4
        
after_script:
  - vendor/bin/test-reporter
